=== Azulin1111/AppMusic/cargadorCanciones2020/ProyectoComponenteCanciones/xml/canciones.xsd
<?xml version ="1.0" encoding ="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.tds.es/canciones" xmlns="http://www.tds.es/canciones"
	elementFormDefault="qualified">
	
	<xs:element name="canciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cancion" type="Cancion" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Cancion">
		<xs:sequence>
			<xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="estilo" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="interprete" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="titulo" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== Azulin1111/AppMusic/cargadorCanciones2020/ProyectoComponenteCanciones/xml/canciones.xml
<?xml version="1.0" ?>
<canciones xmlns="http://www.tds.es/canciones" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://www.tds.es/canciones canciones.xsd">
	
	<cancion titulo="I'll take a melody">
		<URL><![CDATA[https://ia801406.us.archive.org/8/items/tsheaffer2020-11-08/16%20I%27ll%20Take%20A%20Melody.mp3]]></URL>
		<estilo>Folk</estilo>
		<interprete>Todd Sheaffer</interprete>
	</cancion>

	<cancion titulo="La Vie en rose">
		<URL><![CDATA[https://ia801605.us.archive.org/16/items/78_la-vie-en-rose-slow-chante_edith-piaf-louiguy-edith-piaf-chansons-parisiennes-guy_gbia0000684a/La%20Vie%20En%20Rose%20%28Slow%20Chante%29%20-%20Edith%20Piaf-restored.mp3]]></URL>
		<estilo>Cabaret</estilo>
		<interprete>Edith Piaf</interprete>
	</cancion>

	<cancion titulo="In the Court of the Crimson King">
		<URL><![CDATA[https://ia800102.us.archive.org/7/items/cd_in-the-court-of-the-crimson-king_king-crimson/disc1/05.%20King%20Crimson%20-%20The%20Court%20of%20the%20Crimson%20King%20%28including%20The%20Return%20of%20the%20Fire%20Witch%20and%20The%20Dance%20of%20the%20Puppets%29_sample.mp3]]></URL>
		<estilo>Rock-sinfonico</estilo>
		<interprete>King Crimson </interprete>
	</cancion>
	
	<cancion titulo="Confessing that I love you">
		<URL><![CDATA[https://ia600108.us.archive.org/13/items/78_west-end-blues_louis-armstrong-and-his-orchestra-spencer-williams_gbia0031327/06%20-%20Confessin%27%20That%20I%20Love%20You%20-%20Louis%20Armstrong%20And%20His%20Orchcestra.mp3]]></URL>
		<estilo>Jazz</estilo>
		<interprete>Louis Armstrong</interprete>
	</cancion>
	
	<cancion titulo="Moonlight Serenade">
		<URL><![CDATA[https://ia800803.us.archive.org/24/items/78_moonlight-serenade_glenn-miller-and-his-orchestra-glenn-miller_gbia0015151b/Moonlight%20Serenade%20-%20Glenn%20Miller%20and%20his%20Orchestra-restored.mp3]]></URL>
		<estilo>Ballad</estilo>
		<interprete>Glen Miller</interprete>
	</cancion>
	
	<cancion titulo="La Cumparsita">
		<URL><![CDATA[https://ia801609.us.archive.org/14/items/78_la-cumparsita_pietro-g.h.-matos-rodriguez_gbia0001088b/La%20Cumparsita%20-%20Pietro%20-%20G.H.%20Matos%20Rodriguez-restored.mp3]]></URL>
		<estilo>Tango</estilo>
		<interprete>Pietro</interprete>
	</cancion>

</canciones>
